database=mysql
spring.datasource.url=jdbc:mysql://user27-db-mysql.cx8822yqsk9k.eu-west-2.rds.amazonaws.com:3306/petclinic
spring.datasource.username=admin
spring.datasource.password=admin123!
spring.sql.init.mode=always
